name: Instagram Reels Distributor

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        run: |
          npm install
          npx playwright install chromium

      - name: Run
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: node src/main.js

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          git diff --cached --quiet || git commit -m "Update downloaded reels"

          git push
