name: Instagram Reels Distributor

on:
  workflow_dispatch:

jobs:
  reels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npx playwright install chromium

      - run: node src/index.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      - name: Upload Debug Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: savefrom-debug
         path: |
          savefrom.png
          savefrom.html
